In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

/tmp/ipykernel_60003/3824868780.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
2024-04-28 03:34:06.367346: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-28 03:34:06.387698: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-28 03:34

In [2]:
df = pd.read_csv('./input/copper_returns_5d_final.csv')
df.describe()

LMCADS03       LMCADY          DXY          SPX         BCOM  \
count  5539.000000  5539.000000  5539.000000  5539.000000  5539.000000   
mean     -0.000185    -0.000178     0.000007    -0.000252     0.000072   
std       0.016059     0.016464     0.004793     0.011794     0.010250   
min      -0.112019    -0.110645    -0.024921    -0.103782    -0.054910   
25%      -0.008649    -0.008880    -0.002635    -0.005469    -0.005554   
50%       0.000000     0.000000     0.000000    -0.000390     0.000000   
75%       0.007562     0.007760     0.002658     0.003949     0.005375   
max       0.109603     0.109134     0.027541     0.136158     0.066117   

              MXWD          XAU          XAG  LMCADY_acu_5d  LMCADY_std_5d  
count  5539.000000  5539.000000  5539.000000    5539.000000    5539.000000  
mean     -0.000205    -0.000274    -0.000106      -0.000867       0.014218  
std       0.009880     0.010722     0.019587       0.034782       0.008721  
min      -0.085172    -0.097378    -0.123485      -0.185825       0.000805  
25%      -0.004878    -0.005978    -0.009770      -0.021102       0.008616  
50%      -0.000643    -0.000497    -0.000771      -0.001844       0.012148  
75%       0.003807     0.004908     0.008074       0.017065       0.017520  
max       0.105134     0.099792     0.226116       0.259832       0.091981

In [3]:
scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(df.drop(['Date', 'LMCADY_std_5d', 'LMCADY_acu_5d'], axis=1))
print(scaled_features.shape)
scaled_features

(5539, 8)


array([[0.51105054, 0.50820092, 0.46040927, ..., 0.45376117, 0.47765483,
        0.37989689],
       [0.50214433, 0.50261079, 0.51343716, ..., 0.46015831, 0.47895721,
        0.35204686],
       [0.54819756, 0.54585012, 0.39836873, ..., 0.46113695, 0.53109618,
        0.36137883],
       ...,
       [0.45696148, 0.45698224, 0.56849407, ..., 0.35097823, 0.49387949,
        0.34883688],
       [0.44663175, 0.44252277, 0.56989819, ..., 0.42771448, 0.41879554,
        0.31110092],
       [0.42031426, 0.41407919, 0.27142421, ..., 0.32700141, 0.52319187,
        0.33065703]])

In [4]:
def crearSecuencias(data, n_steps):
    X, y = [], []
    try:
        data = data.values  # Asegurarse de que 'data' es un array de NumPy
    except:
        pass
    for i in range(n_steps, len(data)):
        X.append(data[i-n_steps:i, :-2])  # las variables excepto los target
        y.append(data[i, -2:])            # los target
    return np.array(X), np.array(y)

In [5]:
n_steps = 25  # ventana modificable
X, y = crearSecuencias(scaled_features, n_steps)
(X.shape, y.shape)


((5514, 25, 6), (5514, 2))

In [6]:
# verificar que haya secuencia
print(X[0])
print(X[1])

[[0.51105054 0.50820092 0.46040927 0.44423603 0.50432324 0.45376117]
 [0.50214433 0.50261079 0.51343716 0.44530546 0.40553668 0.46015831]
 [0.54819756 0.54585012 0.39836873 0.43838686 0.51559425 0.46113695]
 [0.49410693 0.49374752 0.36140662 0.41908875 0.4375622  0.41213303]
 [0.52996151 0.5302504  0.55430507 0.39575223 0.48212846 0.41553961]
 [0.5619997  0.56257651 0.43096597 0.40912256 0.46098249 0.43504885]
 [0.49701022 0.49452026 0.447426   0.40636799 0.41316342 0.42126043]
 [0.41368416 0.40945351 0.4621292  0.45972953 0.44443493 0.48198419]
 [0.52550391 0.52944731 0.36991284 0.44453469 0.44646772 0.46557395]
 [0.36897736 0.36294137 0.50655397 0.44057081 0.38628919 0.45033045]
 [0.5033649  0.5028788  0.45836768 0.38636589 0.46335062 0.40053972]
 [0.46712256 0.46496218 0.44538254 0.43721685 0.42892662 0.46484468]
 [0.53753126 0.53518463 0.49544358 0.45992226 0.47799601 0.45961024]
 [0.47228924 0.47030131 0.5769906  0.39002791 0.41787082 0.39867988]
 [0.46046999 0.45865672 0.55432041

In [7]:
y

array([[0.47584125, 0.35551757],
       [0.48477789, 0.40260268],
       [0.47073196, 0.29257905],
       ...,
       [0.49387949, 0.34883688],
       [0.41879554, 0.31110092],
       [0.52319187, 0.33065703]])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0)


In [9]:
def rmse(y_true, y_pred):
    return tf.sqrt(tf.reduce_mean(tf.square(y_true - y_pred)))

In [10]:
model = Sequential([

    Conv1D(filters=128, kernel_size=2, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Conv1D(filters=64, kernel_size=2, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Conv1D(filters=32, kernel_size=2, activation='relu'),
    BatchNormalization(),
    MaxPooling1D(pool_size=2),

    Flatten(),

    Dense(100, activation='relu'),
    Dropout(0.5),

    Dense(50, activation='relu'),
    Dropout(0.5),

    Dense(2)
    
])

initial_learning_rate = 0.0001
optimizer = Adam(learning_rate=initial_learning_rate)

model.compile(optimizer=optimizer, loss='mse', metrics=[rmse])


2024-04-28 03:34:07.105259: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-28 03:34:07.125172: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-28 03:34:07.125283: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [11]:
history = model.fit(X_train, y_train, epochs=50, verbose=1, validation_split=0.15,batch_size=64)


Epoch 1/50


2024-04-28 03:34:09.455790: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8904
2024-04-28 03:34:09.875412: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2024-04-28 03:34:09.929399: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2024-04-28 03:34:10.528574: I external/local_xla/xla/service/service.cc:168] XLA service 0x700a98009350 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-04-28 03:34:10.528587: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3080, Compute Capability 8.6
2024-04-28 03:34:10.531796: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1714293250.585273   60114 device_compiler.

63/63 [==============================] - 4s 11ms/step - loss: 2.6375 - rmse: 1.6062 - val_loss: 0.3044 - val_rmse: 0.5517
Epoch 2/50
63/63 [==============================] - 0s 3ms/step - loss: 1.9544 - rmse: 1.3853 - val_loss: 0.3336 - val_rmse: 0.5776
Epoch 3/50
63/63 [==============================] - 0s 3ms/step - loss: 1.4070 - rmse: 1.1758 - val_loss: 0.3091 - val_rmse: 0.5559
Epoch 4/50
63/63 [==============================] - 0s 3ms/step - loss: 1.1480 - rmse: 1.0650 - val_loss: 0.2617 - val_rmse: 0.5115
Epoch 5/50
63/63 [==============================] - 0s 2ms/step - loss: 0.9626 - rmse: 0.9727 - val_loss: 0.2077 - val_rmse: 0.4557
Epoch 6/50
63/63 [==============================] - 0s 2ms/step - loss: 0.7967 - rmse: 0.8844 - val_loss: 0.1518 - val_rmse: 0.3895
Epoch 7/50
63/63 [==============================] - 0s 2ms/step - loss: 0.6699 - rmse: 0.8169 - val_loss: 0.1310 - val_rmse: 0.3618
Epoch 8/50
63/63 [==============================] - 0s 2ms/step - loss: 0.5557 - rmse:

In [12]:
loss = model.evaluate(X_test, y_test)
print(f'Loss on test data: {loss}')


26/26 [==============================] - 0s 4ms/step - loss: 0.0202 - rmse: 0.1419
Loss on test data: [0.020235074684023857, 0.1419147402048111]
